/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ValidaOS;
import DAO.OrdemServicoDAO;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author Alvaro
 */
public class TelaMostraOrdens extends javax.swing.JFrame implements KeyListener {

    /**
     * Creates new form TelaVisualizaOs
     */
    public TelaMostraOrdens() throws SQLException {
        initComponents();
        AtualizaTabelaOs();
        AjustaTabela();
        TxtBuscaOs.addKeyListener(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaOs = new javax.swing.JTable();
        BtnFinalizaOs = new javax.swing.JButton();
        BtnVisualizaOs = new javax.swing.JButton();
        BtnImprimir = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        TxtBuscaOs = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ordens de serviço");

        TabelaOs.setAutoCreateRowSorter(true);
        TabelaOs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TabelaOs.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        TabelaOs.setSelectionBackground(new java.awt.Color(255, 255, 153));
        TabelaOs.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TabelaOs);

        BtnFinalizaOs.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        BtnFinalizaOs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imgs/Checkmark Filled-50.png"))); // NOI18N
        BtnFinalizaOs.setText("Finalizar O.S");
        BtnFinalizaOs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFinalizaOsActionPerformed(evt);
            }
        });

        BtnVisualizaOs.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        BtnVisualizaOs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imgs/Search-48 (1).png"))); // NOI18N
        BtnVisualizaOs.setText("Visualizar O.S");
        BtnVisualizaOs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVisualizaOsActionPerformed(evt);
            }
        });

        BtnImprimir.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        BtnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imgs/Print_48px.png"))); // NOI18N
        BtnImprimir.setText("Imprimir");
        BtnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnImprimirActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText("Buscar O.S.:");

        TxtBuscaOs.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BtnFinalizaOs)
                                .addGap(27, 27, 27)
                                .addComponent(BtnVisualizaOs)
                                .addGap(18, 18, 18)
                                .addComponent(BtnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtBuscaOs, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 208, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtBuscaOs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnFinalizaOs)
                    .addComponent(BtnVisualizaOs)
                    .addComponent(BtnImprimir))
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnFinalizaOsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFinalizaOsActionPerformed
        FinalizaOs();
    }//GEN-LAST:event_BtnFinalizaOsActionPerformed
    private void FinalizaOs() {
        int confirmacao = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja finalizar a OS selecionada?", "Confirmação", JOptionPane.YES_NO_OPTION);
        if (confirmacao == JOptionPane.YES_OPTION) {
            if (TabelaOs.getValueAt(TabelaOs.getSelectedRow(), 5).toString().equals("FECHADA")) {
                JOptionPane.showMessageDialog(null, "OS Selecionada ja se encontra fechada!");
            } else {
                ValidaOS validaFechamentoOs = new ValidaOS();
                validaFechamentoOs.setId_os(TabelaOs.getValueAt(TabelaOs.getSelectedRow(), 0).toString());
                try {
                    validaFechamentoOs.fechaOs();
                } catch (SQLException ex) {
                    Logger.getLogger(TelaMostraOrdens.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

    }
    private void BtnVisualizaOsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVisualizaOsActionPerformed
        abreVisualizacaoOs();
    }//GEN-LAST:event_BtnVisualizaOsActionPerformed
    private void abreVisualizacaoOs() {
        ValidaOS retornaVisualizacao = new ValidaOS();
        TelaNovaOrdemDeServico abreVisualizacao = new TelaNovaOrdemDeServico();
        retornaVisualizacao.setId_os(TabelaOs.getValueAt(TabelaOs.getSelectedRow(), 0).toString());
        retornaVisualizacao.setIdCliente(TabelaOs.getValueAt(TabelaOs.getSelectedRow(), 1).toString());
        String statusOs = TabelaOs.getValueAt(TabelaOs.getSelectedRow(), 5).toString();
        String dadosOs[] = new String[19];
        try {
            dadosOs = retornaVisualizacao.visualizaOs();
        } catch (SQLException ex) {
            Logger.getLogger(TelaMostraOrdens.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        abreVisualizacao.setId_os(Integer.parseInt(TabelaOs.getValueAt(TabelaOs.getSelectedRow(), 0).toString()));
        abreVisualizacao.setNome(dadosOs[1]);
        abreVisualizacao.setBairro(dadosOs[6]);
        abreVisualizacao.setCelular(dadosOs[3]);
        abreVisualizacao.setCidade(dadosOs[7]);
        abreVisualizacao.setCpf(dadosOs[5]);
        abreVisualizacao.setAcessorio(dadosOs[13]);
        abreVisualizacao.setEndereco(dadosOs[4]);
        abreVisualizacao.setEquipamento(dadosOs[18]);
        abreVisualizacao.setMarca(dadosOs[11]);
        abreVisualizacao.setModelo(dadosOs[10]);
        abreVisualizacao.setNumSerie(dadosOs[12]);
        abreVisualizacao.setNumero(dadosOs[9]);
        abreVisualizacao.setTelefone(dadosOs[2]);
        abreVisualizacao.setObsos(dadosOs[15]);
        abreVisualizacao.setEstado(dadosOs[8]);
        abreVisualizacao.setProblemaReclamado(dadosOs[14]);
        abreVisualizacao.setEquipamento(dadosOs[18]);
        abreVisualizacao.setStatusOs(statusOs);
        abreVisualizacao.VisualizaOs();
        abreVisualizacao.setVisible(true);
        try {
            dadosOs = retornaVisualizacao.visualizaOs();
        } catch (SQLException ex) {
            Logger.getLogger(TelaMostraOrdens.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void BtnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnImprimirActionPerformed
        Impressao();
    }//GEN-LAST:event_BtnImprimirActionPerformed
    private void Impressao() {
        OrdemServicoDAO imp = new OrdemServicoDAO();
        //TabelaClientes.getValueAt(TabelaClientes.getSelectedRow(), 0).toString()
        imp.setId_os(TabelaOs.getValueAt(TabelaOs.getSelectedRow(), 0).toString());
        imp.setIdCliente(TabelaOs.getValueAt(TabelaOs.getSelectedRow(), 1).toString());
        try {
            imp.Imprime();
        } catch (JRException ex) {
            Logger.getLogger(TelaMostraOrdens.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TelaMostraOrdens.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void BuscaOs() {
        OrdemServicoDAO dm = new OrdemServicoDAO();
        dm.setSql("SELECT id_os,id_cliente,nome,telefone,problema_reclamado,aberta_fechada,status_os,data_fechamento,data_abertura FROM ordem_servico,cadastro_clientes WHERE cadastro_clientes_id = id_cliente AND nome ILIKE '%" + TxtBuscaOs.getText() + "%' ORDER BY id_os DESC");
        try {
            TabelaOs.setModel(dm.AlimentaTabelaOs());
            AjustaTabela();
        } catch (SQLException e) {
            e.getMessage();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMostraOrdens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMostraOrdens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMostraOrdens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMostraOrdens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TelaMostraOrdens().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(TelaMostraOrdens.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    public void AtualizaTabelaOs() throws SQLException {
        OrdemServicoDAO dm = new OrdemServicoDAO();
        dm.setSql("SELECT id_os,id_cliente,nome,telefone,problema_reclamado,aberta_fechada,status_os,data_abertura FROM ordem_servico,cadastro_clientes WHERE cadastro_clientes_id = id_cliente ORDER BY id_os DESC");
        TabelaOs.setModel(dm.AlimentaTabelaOs());
    }

    private void AjustaTabela() throws SQLException {
        TabelaOs.changeSelection(0, 0, false, false);
        TabelaOs.getColumnModel().getColumn(0).setMinWidth(50);
        TabelaOs.getColumnModel().getColumn(0).setPreferredWidth(50);
        TabelaOs.getColumnModel().getColumn(0).setMaxWidth(50);
        TabelaOs.getColumnModel().getColumn(1).setMinWidth(0);
        TabelaOs.getColumnModel().getColumn(1).setPreferredWidth(0);
        TabelaOs.getColumnModel().getColumn(1).setMaxWidth(0);
        TabelaOs.getColumnModel().getColumn(2).setMinWidth(150);
        TabelaOs.getColumnModel().getColumn(2).setPreferredWidth(150);
        TabelaOs.getColumnModel().getColumn(2).setMaxWidth(150);
        TabelaOs.getColumnModel().getColumn(3).setMinWidth(100);
        TabelaOs.getColumnModel().getColumn(3).setPreferredWidth(100);
        TabelaOs.getColumnModel().getColumn(3).setMaxWidth(100);
        TabelaOs.getColumnModel().getColumn(4).setMinWidth(200);
        TabelaOs.getColumnModel().getColumn(4).setPreferredWidth(200);
        TabelaOs.getColumnModel().getColumn(4).setMaxWidth(200);
        TabelaOs.getColumnModel().getColumn(5).setMinWidth(115);
        TabelaOs.getColumnModel().getColumn(5).setPreferredWidth(115);
        TabelaOs.getColumnModel().getColumn(5).setMaxWidth(115);
        TabelaOs.getColumnModel().getColumn(6).setMinWidth(100);
        TabelaOs.getColumnModel().getColumn(6).setPreferredWidth(100);
        TabelaOs.getColumnModel().getColumn(6).setMaxWidth(100);       
        TabelaOs.changeSelection(0, 0, false, false);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnFinalizaOs;
    private javax.swing.JToggleButton BtnImprimir;
    private javax.swing.JButton BtnVisualizaOs;
    private javax.swing.JTable TabelaOs;
    private javax.swing.JTextField TxtBuscaOs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent e) {
        BuscaOs();
    }

    @Override
    public void keyPressed(KeyEvent e) {

    }

    @Override
    public void keyReleased(KeyEvent e) {

    }
}
