/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ValidaCliente;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Alvaro
 */
public class TelaCadastroAlteracaoVisualizacaoClientes extends javax.swing.JFrame {

    private String Nome, Telefone, Celular, CpfCnpj, Endereco, Numero, Bairro, Cidade, Estado, Mensagem, TituloMensagem;
    private Boolean status = false;
    private String id_cliente;

    public TelaCadastroAlteracaoVisualizacaoClientes() {
        initComponents();
        setIcon();
        if (getId_cliente() != null) {
            LabelTituloCliente.setText("Cliente - Alteração");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LabelNomeCliente = new javax.swing.JLabel();
        LabelEnderecoCliente = new javax.swing.JLabel();
        LabelBairroCliente = new javax.swing.JLabel();
        LabelCidadeCliente = new javax.swing.JLabel();
        LabelCpfCnpjCliente = new javax.swing.JLabel();
        LabelTelefoneCliente = new javax.swing.JLabel();
        LabelCelularCliente = new javax.swing.JLabel();
        LabelNumeroCliente = new javax.swing.JLabel();
        TxtNome = new javax.swing.JTextField();
        TxtCpfCnpj = new javax.swing.JTextField();
        TxtNumeroEndereco = new javax.swing.JTextField();
        TxtEndereco = new javax.swing.JTextField();
        TxtBairro = new javax.swing.JTextField();
        TxtCidade = new javax.swing.JTextField();
        LabelEstadoCliente = new javax.swing.JLabel();
        TxtEstado = new javax.swing.JTextField();
        LabelTituloCliente = new javax.swing.JLabel();
        TxtTelefone = new javax.swing.JFormattedTextField();
        TxtCeluar = new javax.swing.JFormattedTextField();
        BtnLimpar = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();
        BtnSalvar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        OpcSalvar = new javax.swing.JMenuItem();
        OpcCancelar = new javax.swing.JMenuItem();
        OpcLimparCampos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Cliente - Cadastro");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        LabelNomeCliente.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        LabelNomeCliente.setForeground(new java.awt.Color(0, 153, 204));
        LabelNomeCliente.setText("Nome*");

        LabelEnderecoCliente.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        LabelEnderecoCliente.setText("Endereço.:");

        LabelBairroCliente.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        LabelBairroCliente.setText("Bairro.:");

        LabelCidadeCliente.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        LabelCidadeCliente.setText("Cidade.:");

        LabelCpfCnpjCliente.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        LabelCpfCnpjCliente.setForeground(new java.awt.Color(0, 153, 204));
        LabelCpfCnpjCliente.setText("CPF/CNPJ*");

        LabelTelefoneCliente.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        LabelTelefoneCliente.setForeground(new java.awt.Color(0, 153, 204));
        LabelTelefoneCliente.setText("Telefone*");

        LabelCelularCliente.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        LabelCelularCliente.setText("Celular.:");

        LabelNumeroCliente.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        LabelNumeroCliente.setText("Numero.:");

        TxtNome.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        TxtCpfCnpj.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        TxtNumeroEndereco.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        TxtEndereco.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        TxtBairro.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        TxtCidade.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        LabelEstadoCliente.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        LabelEstadoCliente.setText("Estado.:");

        TxtEstado.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        LabelTituloCliente.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        LabelTituloCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTituloCliente.setText("Cliente - Cadastro");

        try {
            TxtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TxtTelefone.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        try {
            TxtCeluar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TxtCeluar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        BtnLimpar.setBackground(new java.awt.Color(204, 204, 204));
        BtnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imgs/Broom-52.png"))); // NOI18N
        BtnLimpar.setText("Limpar    [F2]");
        BtnLimpar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnLimpar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimparActionPerformed(evt);
            }
        });

        BtnCancelar.setBackground(new java.awt.Color(204, 204, 204));
        BtnCancelar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        BtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imgs/Cancel-64.png"))); // NOI18N
        BtnCancelar.setText("Cancelar [ESC]");
        BtnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });

        BtnSalvar.setBackground(new java.awt.Color(204, 204, 204));
        BtnSalvar.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        BtnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imgs/Save Close-50.png"))); // NOI18N
        BtnSalvar.setText("Salvar [ENTER]");
        BtnSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelTituloCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(BtnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelEnderecoCliente)
                            .addComponent(LabelNomeCliente)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(TxtNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                                .addComponent(TxtCpfCnpj, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LabelCpfCnpjCliente, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TxtEndereco, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(LabelCidadeCliente)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(LabelBairroCliente)
                                .addComponent(TxtBairro, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                                .addComponent(TxtCidade)))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelNumeroCliente)
                            .addComponent(TxtNumeroEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(TxtCeluar, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(LabelTelefoneCliente, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(LabelCelularCliente, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TxtTelefone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TxtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelEstadoCliente))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelTituloCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LabelNomeCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(LabelCpfCnpjCliente)
                                .addGap(5, 5, 5)
                                .addComponent(TxtCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(LabelEnderecoCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TxtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtNumeroEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(LabelBairroCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(LabelCidadeCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(LabelTelefoneCliente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TxtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(LabelCelularCliente))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(86, 86, 86)
                                        .addComponent(TxtCeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LabelNumeroCliente)
                                .addGap(117, 117, 117)
                                .addComponent(LabelEstadoCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jMenu1.setText("Opções");

        OpcSalvar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, 0));
        OpcSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imgs/Save Close-16.png"))); // NOI18N
        OpcSalvar.setText("Salvar");
        OpcSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcSalvarActionPerformed(evt);
            }
        });
        jMenu1.add(OpcSalvar);

        OpcCancelar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        OpcCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imgs/Cancel-16.png"))); // NOI18N
        OpcCancelar.setText("Cancelar");
        OpcCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcCancelarActionPerformed(evt);
            }
        });
        jMenu1.add(OpcCancelar);

        OpcLimparCampos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        OpcLimparCampos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imgs/Broom-16.png"))); // NOI18N
        OpcLimparCampos.setText("Limpar campos");
        OpcLimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcLimparCamposActionPerformed(evt);
            }
        });
        jMenu1.add(OpcLimparCampos);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void OpcSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcSalvarActionPerformed
        try {
            realizarCadastroAlteracao();
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastroAlteracaoVisualizacaoClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_OpcSalvarActionPerformed


    private void OpcCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcCancelarActionPerformed
        CancelaCadastro();
    }//GEN-LAST:event_OpcCancelarActionPerformed

    private void OpcLimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcLimparCamposActionPerformed
        limpaCampos();
    }//GEN-LAST:event_OpcLimparCamposActionPerformed

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        CancelaCadastro();
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void BtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalvarActionPerformed
        try {
            realizarCadastroAlteracao();
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastroAlteracaoVisualizacaoClientes.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_BtnSalvarActionPerformed
    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        CancelaCadastro();

    }//GEN-LAST:event_formWindowClosing

    private void BtnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimparActionPerformed
        limpaCampos();
    }//GEN-LAST:event_BtnLimparActionPerformed
    private void CancelaCadastro() {
        int CancelaSimOuNao;
        CancelaSimOuNao = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?", "Confirmação", JOptionPane.YES_NO_OPTION);

        if (CancelaSimOuNao == JOptionPane.YES_OPTION) {
            this.dispose();
            if (getStatus() == true) {
                try {
                    new TelaMostraClientesCadastrados().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(TelaCadastroAlteracaoVisualizacaoClientes.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        }
    }

    private void realizarCadastroAlteracao() throws SQLException {
        if (getId_cliente() == null) {
            //Nome,Telefone,Celular,CpfCnpj,Endereco,Numero,Bairro,Cidade,Estado
            ValidaCliente controle = new ValidaCliente();
            controle.setNome(TxtNome.getText());
            controle.setTelefone(TxtTelefone.getText());
            controle.setCelular(TxtCeluar.getText());
            controle.setCpfCnpj(TxtCpfCnpj.getText());
            controle.setEndereco(TxtEndereco.getText());
            controle.setNumero(TxtNumeroEndereco.getText());
            controle.setBairro(TxtBairro.getText());
            controle.setCidade(TxtCidade.getText());
            controle.setEstado(TxtEstado.getText());
            controle.validaCampos();

        } else {
            ValidaCliente controle = new ValidaCliente();
            controle.setId_cliente(getId_cliente());
            controle.setNome(TxtNome.getText());
            controle.setTelefone(TxtTelefone.getText());
            controle.setCelular(TxtCeluar.getText());
            controle.setCpfCnpj(TxtCpfCnpj.getText());
            controle.setEndereco(TxtEndereco.getText());
            controle.setNumero(TxtNumeroEndereco.getText());
            controle.setBairro(TxtBairro.getText());
            controle.setCidade(TxtCidade.getText());
            controle.setEstado(TxtEstado.getText());
            controle.validaCampos();
        }

    }

    public void AlimentaCampos() {
        if (getMensagem().equals("Alteração")) {
            BtnLimpar.setEnabled(false);
            OpcLimparCampos.setEnabled(false);
        }
        LabelTituloCliente.setText("Cliente - " + getMensagem());
        TxtBairro.setText(getBairro());
        TxtCeluar.setText(getCelular());
        TxtCidade.setText(getCidade());
        TxtCpfCnpj.setText(getCpfCnpj());
        TxtEndereco.setText(getEndereco());
        TxtEstado.setText(getEstado());
        TxtNome.setText(getNome());
        TxtNumeroEndereco.setText(getNumero());
        TxtTelefone.setText(getTelefone());
    }

    public void DisativaCampos() {
        BtnLimpar.setEnabled(false);
        BtnSalvar.setEnabled(false);
        OpcLimparCampos.setVisible(false);
        OpcSalvar.setEnabled(false);
        TxtBairro.setEditable(false);
        TxtCeluar.setEditable(false);
        TxtCidade.setEditable(false);
        TxtCpfCnpj.setEditable(false);
        TxtEndereco.setEditable(false);
        TxtEstado.setEditable(false);
        TxtNome.setEditable(false);
        TxtNumeroEndereco.setEditable(false);
        TxtTelefone.setEditable(false);
    }

    public void exibeMensagens() {
        if (getStatus() == true) {
            JOptionPane.showMessageDialog(null, "Cliente cadastrado com sucesso!", "Cliente Cadastrado", JOptionPane.INFORMATION_MESSAGE);
            limpaCampos();
        } else {
            JOptionPane.showMessageDialog(null, "Falha ao cadastrar usuario, tente novamente!\n"
                    + "Certifique-se de ter preenchido todos os campos que possuem (*)", "Falha", 0);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroAlteracaoVisualizacaoClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroAlteracaoVisualizacaoClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroAlteracaoVisualizacaoClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroAlteracaoVisualizacaoClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroAlteracaoVisualizacaoClientes().setVisible(true);
            }
        });
    }

    private void limpaCampos() {
        TxtNome.setText("");
        TxtTelefone.setText("");
        TxtCeluar.setText("");
        TxtCpfCnpj.setText("");
        TxtEndereco.setText("");
        TxtNumeroEndereco.setText("");
        TxtBairro.setText("");
        TxtCidade.setText("");
        TxtEstado.setText("");
    }

    public String getNome() {
        return Nome;
    }

    public void setNome(String Nome) {
        this.Nome = Nome;
    }

    public String getTelefone() {
        return Telefone;
    }

    public void setTelefone(String Telefone) {
        this.Telefone = Telefone;
    }

    public String getCelular() {
        return Celular;
    }

    public void setCelular(String Celular) {
        this.Celular = Celular;
    }

    public String getCpfCnpj() {
        return CpfCnpj;
    }

    public void setCpfCnpj(String CpfCnpj) {
        this.CpfCnpj = CpfCnpj;
    }

    public String getEndereco() {
        return Endereco;
    }

    public void setEndereco(String Endereco) {
        this.Endereco = Endereco;
    }

    public String getNumero() {
        return Numero;
    }

    public void setNumero(String Numero) {
        this.Numero = Numero;
    }

    public String getBairro() {
        return Bairro;
    }

    public void setBairro(String Bairro) {
        this.Bairro = Bairro;
    }

    public String getCidade() {
        return Cidade;
    }

    public void setCidade(String Cidade) {
        this.Cidade = Cidade;
    }

    public String getEstado() {
        return Estado;
    }

    public void setEstado(String Estado) {
        this.Estado = Estado;
    }

    public String getMensagem() {
        return Mensagem;
    }

    public void setMensagem(String Mensagem) {
        this.Mensagem = Mensagem;
    }

    public Boolean getStatus() {
        return status;
    }

    public void setStatus(Boolean status) {
        this.status = status;
    }

    public String getId_cliente() {
        return id_cliente;
    }

    public void setId_cliente(String id_cliente) {
        this.id_cliente = id_cliente;
    }

    public String getTituloMensagem() {
        return TituloMensagem;
    }

    public void setTituloMensagem(String TituloMensagem) {
        this.TituloMensagem = TituloMensagem;
    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/view/imgs/User-100.png")));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnCancelar;
    public javax.swing.JButton BtnLimpar;
    public javax.swing.JButton BtnSalvar;
    public javax.swing.JLabel LabelBairroCliente;
    public javax.swing.JLabel LabelCelularCliente;
    public javax.swing.JLabel LabelCidadeCliente;
    public javax.swing.JLabel LabelCpfCnpjCliente;
    public javax.swing.JLabel LabelEnderecoCliente;
    public javax.swing.JLabel LabelEstadoCliente;
    public javax.swing.JLabel LabelNomeCliente;
    public javax.swing.JLabel LabelNumeroCliente;
    public javax.swing.JLabel LabelTelefoneCliente;
    public javax.swing.JLabel LabelTituloCliente;
    public javax.swing.JMenuItem OpcCancelar;
    public javax.swing.JMenuItem OpcLimparCampos;
    public javax.swing.JMenuItem OpcSalvar;
    public javax.swing.JTextField TxtBairro;
    public javax.swing.JFormattedTextField TxtCeluar;
    public javax.swing.JTextField TxtCidade;
    public javax.swing.JTextField TxtCpfCnpj;
    public javax.swing.JTextField TxtEndereco;
    public javax.swing.JTextField TxtEstado;
    public javax.swing.JTextField TxtNome;
    public javax.swing.JTextField TxtNumeroEndereco;
    public javax.swing.JFormattedTextField TxtTelefone;
    public javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
